// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAif3w87MxhcdU9XKEMt6EBY-bEC7e8V-U',
    appId: '1:1078953577660:web:a935eecc09e504c16a54b9',
    messagingSenderId: '1078953577660',
    projectId: 'ints-app',
    authDomain: 'ints-app.firebaseapp.com',
    storageBucket: 'ints-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2MEZFu_shUabJTp1WeJzICaucVK80iFk',
    appId: '1:1078953577660:android:e81537850bd8296b6a54b9',
    messagingSenderId: '1078953577660',
    projectId: 'ints-app',
    storageBucket: 'ints-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjtC9rUFeGnBIAw9esKsbL_SB9Aysrc-8',
    appId: '1:1078953577660:ios:d982a9f571ac77c36a54b9',
    messagingSenderId: '1078953577660',
    projectId: 'ints-app',
    storageBucket: 'ints-app.appspot.com',
    iosBundleId: 'com.example.instApp',
  );
}
